---
title: "Foundations in R Assignment pt 2"
author: "Amanda Mae Woodward"
date: "2026-09-24"
output: html_document
---

For your second R Assignment, complete the questions below. Remember, weekly assignments are graded based on attempts and accuracy, so it's ok if you don't get everything immediately. Please submit your answers by 1) updating this file in your GitHub repository and 2) uploading a .html file of the assignment to this repository. Please submit a link to the repository on Canvas. 

# Set up
1. Load the tidyverse library. 
2. Load the billboard data. 
3. Describe the dataset. 
4. Print the column names from this dataset. 
5. Print the first 5 entries in the dataset. 

# Practice
1. Create a subset of data that has Jay-Z as the only artist. How many songs are in it?
2. In the original dataset, use filter to find information about the song "All the small things." What was the highest position (i.e. lowest number) this song reached on the billboard 100? 
3. Create a subset of data for songs Tim McGraw sang. Summarize the data for wk 1.
4. Create a function that can be used to determine if Britney Spears sang the song. 
5. Test your function on the billboard data. Save the results to a new column called "wasItBritney"
6. Use a for loop to determine if a song placed 50 or below or placed above 50 during the first week. 
7. Use an if else statement to determine the same information as you obtained with the for loop. 
8. Compare your results in 6 and 7. 